services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "/usr/bin/supervisord -n"
    ports:
      - "3000:3000"
      - "3035:3035"
    stdin_open: true
    tty: true
    links:
      - db
    environment:
      DB_USER: root
      DB_PWD: example
      RAILS_ENV: development
    volumes:
      - ./:/home
  
